# Generated by Django 3.2.8 on 2021-11-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211102_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tags',
            new_name='skill',
        ),
    ]
